### ISSUE TITLE
Reconsider repository as template, git strategy

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/motherhen#19]
@trickypr I really want some feedback on this.

With the `mach package` branch, this is almost ready to move to the next stage: designing a configuration to generate source directories.

At that point, there's several aspects to consider.  How do we:

- get the unmodified Mozilla repository?
  - hg or git clone?
  - From the user's repository, or direct from Mozilla's official repositories?
  - Preserve a local "fresh" copy in a git-ignored subdirectory of this repository?
  - Getting a particular branch / tag (Central, Beta, Release, ESR)
- manage the integration of potentially two repositories? (the user's custom code, the stock Mozilla code)
  - Applying the custom patches to make the build viable, _maybe_ committing that to the local Mozilla
- apply the boilerplate code to the Mozilla repository? Several options:
  - Directly commit to a clone of the Mozilla repository
  - git submodule
  - git subtree
  - [hg subtree](https://www.mercurial-scm.org/wiki/HgSubtree) extension
  - an ignored symbolic link
- provide user-interface to generate a branded application?
  - NodeJS / TypeScript class modules
    - file / repo work
    - command-line interface
    - HTML wizard interface with small ExpressJS server
  - Should this really be a template, or should the user run a script from this repository to set everything up?  Probably too complex for a template repo.
- write a test application for this?
  - App should send a HTTP request to a localhost HTTP server
  - Pull a GUID from the application's command line to include in the request
  - HTTP server to resolve the request, and a Promise from the test on receipt
  - Before test runs, generate the application source and build it
  - Test runs the application and provides the GUID to the command line

**Comment by ajvincent** [comment]
I should be clear here: I've always envisioned two, maybe three repositories:

1. The Mozilla repository, possibly as a user-hosted clone
2. This repository, in a clean slate
3. (Maybe) The user's Mozilla subdirectory, which this repository provides an user-interface to generate.

**Comment by trickypr** [comment]
I will look more into this when I get more time, so at some point after tomorrows exam.

**Comment by trickypr** [comment]
I can provide some feedback on how I handle this kind of thing when working on forks, although this might not be ideal for this project:
> get the unmodified Mozilla repository? 

The way I handle this is downloading a zip version of the source from [mozilla's archives](https://archive.mozilla.org/pub/firefox/releases/) and then initialism a git repo around it and creating a commit containing all of the source. This allows me to pin branch and the version of that branch fairly easily.

The main downside is that init + creating branch + commit can take a lot of time (~3min on Linux, ~12 min on Windows)

> manage the integration of potentially two repositories?

- I apply the patches on top firefox's source, but don't commit them, which makes it easy to revert a file or all the patches by just discarding uncommitted changes. This requires every patch to only include one file though. 
- It might be better to make each patch a commit, so you can attach a description and include multiple files

> apply the boilerplate code to the Mozilla repository?

- I handle this by keeping code in a separate directory that follows the same structure as I want it to be included in firefox's source and create symlinks to files and folders. However, this is optimized for inserting files throughout the tree rather than just in one spot

> provide user-interface to generate a branded application?

- A CLI would fit more with my preconceived idea of a build tool
- Alternatively you could build a website on ghpages for converting images. You can [resize images](https://hacks.mozilla.org/2011/01/how-to-develop-a-html5-image-uploader/) and [create a zip file](https://github.com/Touffy/client-zip) client side so it might be possible 

> write a test application for this? 

Like a test build tool? Or a test ui for generating branding?

### Slight disclaimer
A lot of my decisions here come from how I already do things, so there might be better ways of handling things that I haven't thought of.

**Comment by ajvincent** [comment]
I've figured out the basic approach I want to take.  The problem has arisen, conceptually, from having _one_ Mozilla local copy per project... when I think we need to support _two_: a "vanilla" or "pure" copy and an "integrated" copy with the Motherhen project embedded.

Here's what I'm thinking:

1. The configuration references a local "vanilla" or "pure" Mozilla local copy.  This is one Motherhen doesn't touch, except possibly to call `hg unbundle` to get it if it doesn't exist.  (The configuration should also specify a particular tag to use for this case: "esr102" for example.)
2. The configuration references an "integrated" Mozilla local copy, which will have the Motherhen template as a subdirectory via symbolic link.  This will _not_ initially exist: we'll create it via cloning or exporting the vanilla copy, then adding in the Motherhen template.  
3. From this point on, it's the user's responsibility to manage the repositories.  We may support a `npm run push [target]` command to push non-Motherhen changes back to the "vanilla" repository.
4. The configuration references the name of the target directory for the Motherhen symbolic link.
5. Several configurations can live in `.motherhen-config.json`, which will be a dictionary of configurations.  "default" will be the only dictionary key we require.  This configuration file will be git-ignored in this repository.
6. `npm run configure [target]` will set up the integrated copy.
7. Cloning operations should happen in a NodeJS worker thread, so wizards can continue asking questions and getting answers.

This gives us the ability to mix-and-match a Motherhen project with several Mozilla code bases:

- esr
- release
- beta
- central
- whatever local copy the user wants to fetch

We can then keep this repository as a template.  Renaming `boilerplate` to `source` would be appropriate too.

**Comment by ajvincent** [comment]
I'm going ahead with the template choice.  Reconsideration is done.
